### ISSUE TITLE
wrong ws port in README

### ISSUE THREAD

**Issue by havefunbc** [w3tech/bas-devnet-setup#4]
![image](https://user-images.githubusercontent.com/79405048/168939313-119857e7-dc6c-4e08-ab54-c97d4cc48fed.png)

**Comment by hedwig0x** [comment]
Thanks, its fixed here

https://github.com/Ankr-network/bas-devnet-setup/commit/cd71a2f57a5b392e37d12f9d7249a13d4c321ac1
