### ISSUE TITLE
not successfully start 4000 port 

### ISSUE THREAD

**Issue by ThreeAndTwo** [w3tech/bas-devnet-setup#5]
<img width="891" alt="image" src="https://user-images.githubusercontent.com/35927054/171564014-50784798-39e9-4e17-8a38-5362039c04d2.png">

**Comment by hedwig0x** [comment]
Maybe you can find something in the container logs? Looks not clear how to understand what is the problem from list of ports.

**Comment by hedwig0x** [comment]
Also better to check blockscout logs, explorer doesn't relays to the BAS setup. Also there is separate command for running explorer independently.
