### ISSUE TITLE
ankrnetwork/bas-template-bsc:devel not found

### ISSUE THREAD

**Issue by hoanghiep** [w3tech/bas-devnet-setup#8]
Hi There

![lost](https://user-images.githubusercontent.com/1551503/190112886-7e9777e5-06b3-465c-8e5b-370805a1ba04.PNG)

**Comment by bestdev1212** [comment]
You can find it on another repository.

**Comment by hoanghiep** [comment]
@topTalent1212  Did you install successfully with other image?

**Comment by bestdev1212** [comment]
@hoanghiep You can find it now in ankrnetwork repository. It has been missed for a few days, but it's recovered now.

**Comment by hoanghiep** [comment]
@topTalent1212 
Hi. Can you change default currency symbol (BAS) to other name?
